package com.wwd.service.modules.wwd.dto;

import feihua.jdbc.api.pojo.BaseConditionDto;

import java.util.Date;
import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table wwd_user
 *
 * @mbg.generated 2018-04-25 11:35:15
 */
public class SearchWwdUsersConditionDto extends BaseConditionDto {

    //关键字
    private String keyword;
    //性别
    private String gender;

    //学历
    private String education;

    private String homeProvinceId;
    private String homeCityId;
    private String homeDistrictId;
    private String nowProvinceId;
    private String nowCityId;
    private String nowDistrictId;

    private Date ageStart;
    private Date ageEnd;

    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getEducation() {
        return education;
    }

    public void setEducation(String education) {
        this.education = education;
    }

    public String getHomeProvinceId() {
        return homeProvinceId;
    }

    public void setHomeProvinceId(String homeProvinceId) {
        this.homeProvinceId = homeProvinceId;
    }

    public String getHomeCityId() {
        return homeCityId;
    }

    public void setHomeCityId(String homeCityId) {
        this.homeCityId = homeCityId;
    }

    public String getHomeDistrictId() {
        return homeDistrictId;
    }

    public void setHomeDistrictId(String homeDistrictId) {
        this.homeDistrictId = homeDistrictId;
    }

    public String getNowProvinceId() {
        return nowProvinceId;
    }

    public void setNowProvinceId(String nowProvinceId) {
        this.nowProvinceId = nowProvinceId;
    }

    public String getNowCityId() {
        return nowCityId;
    }

    public void setNowCityId(String nowCityId) {
        this.nowCityId = nowCityId;
    }

    public String getNowDistrictId() {
        return nowDistrictId;
    }

    public void setNowDistrictId(String nowDistrictId) {
        this.nowDistrictId = nowDistrictId;
    }

    public Date getAgeStart() {
        return ageStart;
    }

    public void setAgeStart(Date ageStart) {
        this.ageStart = ageStart;
    }

    public Date getAgeEnd() {
        return ageEnd;
    }

    public void setAgeEnd(Date ageEnd) {
        this.ageEnd = ageEnd;
    }
}