package com.wwd.service.mapper;

import com.wwd.service.modules.wwd.po.WwdParticipate;
import feihua.jdbc.api.dao.CrudDao;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by MyBatis Generator.
 * @author revolver 2019-03-12 09:34:55
 */
public interface WwdParticipateMapper extends feihua.jdbc.api.dao.CrudDao<WwdParticipate, String> {
    java.util.List<WwdParticipate> searchWwdParticipates(@Param("entity") com.wwd.service.modules.wwd.dto.SearchWwdParticipatesConditionDto dto);
}