package com.wwd.service.mapper;

import com.wwd.service.modules.wwd.po.WwdUserParamQrcodePo;
import feihua.jdbc.api.dao.CrudDao;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-05-17 10:57:54
 */
public interface WwdUserParamQrcodePoMapper extends feihua.jdbc.api.dao.CrudDao<WwdUserParamQrcodePo, String> {
}