package com.wwd.service.mapper;

import com.wwd.service.modules.wwd.dto.SearchWwdUserEnjoysConditionDto;
import com.wwd.service.modules.wwd.po.WwdUserEnjoyPo;
import feihua.jdbc.api.dao.CrudDao;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2018-05-19 15:53:51
 */
public interface WwdUserEnjoyPoMapper extends feihua.jdbc.api.dao.CrudDao<WwdUserEnjoyPo, String> {

    java.util.List<WwdUserEnjoyPo> searchWwdUserEnjoys(SearchWwdUserEnjoysConditionDto dto);

    /**
     * 查询都有意思的人
     * @param wwdUserId
     * @return
     */
    java.util.List<WwdUserEnjoyPo> selectEnjoyedByWwdUserId(String wwdUserId);
    /**
     * 查询我有意思的人
     * @param wwdUserId
     * @param type
     * @param typeLimit
     * @return
     */
    java.util.List<WwdUserEnjoyPo> selectByWwdUserId(@Param("wwdUserId") String wwdUserId,@Param("type")  String type ,@Param("typeLimit")  String typeLimit);
}