package com.wwd.web.modules.wwd.dto;

import com.feihua.framework.rest.dto.UpdateFormDto;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table wwd_user_visit
 *
 * @mbg.generated 2019-06-17 13:29:29
*/
public class UpdateWwdUserVisit extends UpdateFormDto {
    private String id;

    private String wwdUserId;

    private String visitWwdUserId;

    private String visitWwdUserName;

    private String visitWwdUserGender;

    private String visitWwdUserPic;

    private String visitType;

    private String readFlag;

    private String dataUserId;

    private String dataOfficeId;

    private String dataType;

    private String dataAreaId;

    private String delFlag;

    private Date createAt;

    private String createBy;

    private Date updateAt;

    private String updateBy;

    public String getReadFlag() {
        return readFlag;
    }

    public void setReadFlag(String readFlag) {
        this.readFlag = readFlag;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getWwdUserId() {
        return wwdUserId;
    }

    public void setWwdUserId(String wwdUserId) {
        this.wwdUserId = wwdUserId;
    }

    public String getVisitWwdUserId() {
        return visitWwdUserId;
    }

    public void setVisitWwdUserId(String visitWwdUserId) {
        this.visitWwdUserId = visitWwdUserId;
    }

    public String getVisitWwdUserName() {
        return visitWwdUserName;
    }

    public void setVisitWwdUserName(String visitWwdUserName) {
        this.visitWwdUserName = visitWwdUserName;
    }

    public String getVisitWwdUserGender() {
        return visitWwdUserGender;
    }

    public void setVisitWwdUserGender(String visitWwdUserGender) {
        this.visitWwdUserGender = visitWwdUserGender;
    }

    public String getVisitWwdUserPic() {
        return visitWwdUserPic;
    }

    public void setVisitWwdUserPic(String visitWwdUserPic) {
        this.visitWwdUserPic = visitWwdUserPic;
    }

    public String getVisitType() {
        return visitType;
    }

    public void setVisitType(String visitType) {
        this.visitType = visitType;
    }

    public String getDataUserId() {
        return dataUserId;
    }

    public void setDataUserId(String dataUserId) {
        this.dataUserId = dataUserId;
    }

    public String getDataOfficeId() {
        return dataOfficeId;
    }

    public void setDataOfficeId(String dataOfficeId) {
        this.dataOfficeId = dataOfficeId;
    }

    public String getDataType() {
        return dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public String getDataAreaId() {
        return dataAreaId;
    }

    public void setDataAreaId(String dataAreaId) {
        this.dataAreaId = dataAreaId;
    }

    public String getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    public Date getCreateAt() {
        return createAt;
    }

    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    public String getCreateBy() {
        return createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public Date getUpdateAt() {
        return updateAt;
    }

    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    public String getUpdateBy() {
        return updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }
}