package com.wwd.service.impl;

import com.github.pagehelper.Page;
import com.wwd.Constants;
import com.wwd.service.mapper.WwdUserPoMapper;
import com.wwd.service.modules.wwd.api.ApiWwdParticipateService;
import com.wwd.service.modules.wwd.api.ApiWwdUserPoService;
import com.wwd.service.modules.wwd.dto.SearchWwdParticipatesConditionDto;
import com.wwd.service.modules.wwd.dto.WwdParticipateDto;
import com.wwd.service.modules.wwd.po.WwdParticipate;
import com.wwd.service.modules.wwd.po.WwdUserPo;
import feihua.jdbc.api.pojo.BasePo;
import feihua.jdbc.api.pojo.PageResultDto;
import feihua.jdbc.api.service.impl.ApiBaseServiceImpl;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * This class was generated by MyBatis Generator.
 * @author revolver 2019-03-12 09:34:55
 */
@Service
public class ApiWwdParticipateServiceImpl extends ApiBaseServiceImpl<WwdParticipate, WwdParticipateDto, String> implements ApiWwdParticipateService {
    @Autowired
    com.wwd.service.mapper.WwdParticipateMapper WwdParticipateMapper;

    @Autowired
    WwdUserPoMapper wwdUserPoMapper;

    public ApiWwdParticipateServiceImpl() {
        super(WwdParticipateDto.class);
    }

    @Override
    public PageResultDto<WwdParticipateDto> searchWwdParticipatesDsf(com.wwd.service.modules.wwd.dto.SearchWwdParticipatesConditionDto dto, feihua.jdbc.api.pojo.PageAndOrderbyParamDto pageAndOrderbyParamDto) {
        Page p = super.pageAndOrderbyStart(pageAndOrderbyParamDto);
        List<com.wwd.service.modules.wwd.dto.WwdParticipateDto> list = this.wrapDtos(WwdParticipateMapper.searchWwdParticipates(dto));
        return new PageResultDto(list, this.wrapPage(p));
    }

    @Override
    public List<WwdParticipate> selectByActivityIdAndWwdUserId(String activityId, String wwdUserId) {
        if(StringUtils.isAnyEmpty(activityId,wwdUserId)) return null;
        WwdParticipate wwdParticipate = new WwdParticipate();
        wwdParticipate.setWwdActivityId(activityId);
        wwdParticipate.setWwdUserId(wwdUserId);
        wwdParticipate.setDelFlag(BasePo.YesNo.N.name());
        return selectListSimple(wwdParticipate);
    }

    @Override
    public List<WwdParticipate> selectByActivityIdAndWwdUserIdAndParticipateStatus(String activityId, String wwdUserId, Constants.WwdParticipateStatus wwdParticipateStatus) {
        if(StringUtils.isAnyEmpty(activityId,wwdUserId)) return null;
        WwdParticipate wwdParticipate = new WwdParticipate();
        wwdParticipate.setWwdActivityId(activityId);
        wwdParticipate.setWwdUserId(wwdUserId);
        wwdParticipate.setDelFlag(BasePo.YesNo.N.name());
        wwdParticipate.setStatus(wwdParticipateStatus.getCode());
        return selectListSimple(wwdParticipate);
    }

    @Override
    public int selectCountPaidParticipate(String activityId) {
        if(StringUtils.isEmpty(activityId))
        return 0;
        SearchWwdParticipatesConditionDto dto = new SearchWwdParticipatesConditionDto();
        dto.setWwdActivityId(activityId);
        dto.setPayStatusArr(new String[]{Constants.PayStatus.paid.name(),Constants.PayStatus.offline_pay.name()});
        List<WwdParticipate> wwdParticipates = WwdParticipateMapper.searchWwdParticipates(dto);
        return wwdParticipates == null? 0:wwdParticipates.size();
    }

    @Override
    public int selectCountPaidParticipate(String activityId, String gender) {
        if(StringUtils.isAnyEmpty(activityId, gender))
            return 0;
		SearchWwdParticipatesConditionDto dto = new SearchWwdParticipatesConditionDto();
		dto.setWwdActivityId(activityId);
		dto.setPayStatusArr(new String[]{Constants.PayStatus.paid.name(),Constants.PayStatus.offline_pay.name()});
		List<WwdParticipate> wwdParticipates = WwdParticipateMapper.searchWwdParticipates(dto);

        List<String> wwdUserId = new ArrayList<>();
        if(wwdParticipates != null && !wwdParticipates.isEmpty()){
            for (WwdParticipate participate : wwdParticipates) {
                wwdUserId.add(participate.getWwdUserId());
            }
        }

        if(wwdUserId != null && !wwdUserId.isEmpty()){
            List<WwdUserPo> wwdUserPos = wwdUserPoMapper.selectByPrimaryKeys(wwdUserId,false);
            if(wwdUserPos != null){
                int r= 0;
                for (WwdUserPo wwdUserPo : wwdUserPos) {
                    if(gender.equals(wwdUserPo.getGender())){
                        r++;
                    }
                }
                return r;
            }
        }
        return 0;
    }

    @Override
    public WwdParticipateDto wrapDto(WwdParticipate po) {
        if (po == null) { return null; }
        WwdParticipateDto dto = new WwdParticipateDto();
        dto.setId(po.getId());
        dto.setWwdActivityId(po.getWwdActivityId());
        dto.setWwdUserId(po.getWwdUserId());
        dto.setType(po.getType());
        dto.setPayStatus(po.getPayStatus());
        dto.setStatus(po.getStatus());
        dto.setRemarks(po.getRemarks());
        dto.setDataUserId(po.getDataUserId());
        dto.setDataOfficeId(po.getDataOfficeId());
        dto.setDataType(po.getDataType());
        dto.setDataAreaId(po.getDataAreaId());
        dto.setUpdateAt(po.getUpdateAt());
        dto.setCreateAt(po.getCreateAt());
        dto.setName(po.getName());
        dto.setMobile(po.getMobile());
        dto.setIdCardNo(po.getIdCardNo());
        dto.setIdType(po.getIdType());
        return dto;
    }
}