package com.wwd.service.impl;

import com.github.pagehelper.Page;
import com.wwd.service.modules.wwd.api.ApiWwdParticipateService;
import com.wwd.service.modules.wwd.dto.WwdParticipateDto;
import com.wwd.service.modules.wwd.po.WwdParticipate;
import feihua.jdbc.api.pojo.PageResultDto;
import feihua.jdbc.api.service.impl.ApiBaseServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * This class was generated by MyBatis Generator.
 * @author revolver 2019-03-12 09:34:55
 */
@Service
public class ApiWwdParticipateServiceImpl extends ApiBaseServiceImpl<WwdParticipate, WwdParticipateDto, String> implements ApiWwdParticipateService {
    @Autowired
    com.wwd.service.mapper.WwdParticipateMapper WwdParticipateMapper;

    public ApiWwdParticipateServiceImpl() {
        super(WwdParticipateDto.class);
    }

    @Override
    public PageResultDto<WwdParticipateDto> searchWwdParticipatesDsf(com.wwd.service.modules.wwd.dto.SearchWwdParticipatesConditionDto dto, feihua.jdbc.api.pojo.PageAndOrderbyParamDto pageAndOrderbyParamDto) {
        Page p = super.pageAndOrderbyStart(pageAndOrderbyParamDto);
        List<com.wwd.service.modules.wwd.dto.WwdParticipateDto> list = this.wrapDtos(WwdParticipateMapper.searchWwdParticipates(dto));
        return new PageResultDto(list, this.wrapPage(p));
    }

    @Override
    public WwdParticipateDto wrapDto(WwdParticipate po) {
        if (po == null) { return null; }
        WwdParticipateDto dto = new WwdParticipateDto();
        dto.setId(po.getId());
        dto.setWwdActivityId(po.getWwdActivityId());
        dto.setWwdUserId(po.getWwdUserId());
        dto.setType(po.getType());
        dto.setPayStatus(po.getPayStatus());
        dto.setStatus(po.getStatus());
        dto.setRemarks(po.getRemarks());
        dto.setDataUserId(po.getDataUserId());
        dto.setDataOfficeId(po.getDataOfficeId());
        dto.setDataType(po.getDataType());
        dto.setDataAreaId(po.getDataAreaId());
        dto.setUpdateAt(po.getUpdateAt());
        return dto;
    }
}