package com.wwd.service.modules.wwd.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-06-21 12:59:13
 * Database Table Remarks:
 *   汪汪队活动用户互选表
 *
 * This class corresponds to the database table wwd_activity_user_mutual_election
 * @mbg.generated do_not_delete_during_merge 2019-06-21 12:59:13
*/
public class WwdActivityUserMutualElectionPo extends feihua.jdbc.api.pojo.BasePo<String> {
    /**
     * Database Column Remarks:
     *   活动id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_activity_user_mutual_election.ACTIVITY_ID
     *
     * @mbg.generated 2019-06-21 12:59:13
     */
    private String activityId;

    /**
     * Database Column Remarks:
     *   汪汪队用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_activity_user_mutual_election.WWD_USER_ID
     *
     * @mbg.generated 2019-06-21 12:59:13
     */
    private String wwdUserId;

    /**
     * Database Column Remarks:
     *   选择的汪汪队用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_activity_user_mutual_election.SELECTED_WWD__USER_ID
     *
     * @mbg.generated 2019-06-21 12:59:13
     */
    private String selectedWwdUserId;

    public String getActivityId() {
        return activityId;
    }

    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    public String getWwdUserId() {
        return wwdUserId;
    }

    public void setWwdUserId(String wwdUserId) {
        this.wwdUserId = wwdUserId;
    }

    public String getSelectedWwdUserId() {
        return selectedWwdUserId;
    }

    public void setSelectedWwdUserId(String selectedWwdUserId) {
        this.selectedWwdUserId = selectedWwdUserId;
    }

    public com.wwd.service.modules.wwd.api.ApiWwdActivityUserMutualElectionPoService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.wwd.service.modules.wwd.api.ApiWwdActivityUserMutualElectionPoService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", activityId=").append(activityId);
        sb.append(", wwdUserId=").append(wwdUserId);
        sb.append(", selectedWwdUserId=").append(selectedWwdUserId);
        sb.append("]");
        return sb.toString();
    }
}