package com.wwd.service.modules.wwd.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-11-06 09:49:13
 * Database Table Remarks:
 *   轮播图
 *
 * This class corresponds to the database table wwd_banner
 * @mbg.generated do_not_delete_during_merge 2019-11-06 09:49:13
*/
public class WwdBanner extends feihua.jdbc.api.pojo.BasePo<String> {
    /**
     * Database Column Remarks:
     *   标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_banner.title
     *
     * @mbg.generated 2019-11-06 09:49:13
     */
    private String title;

    /**
     * Database Column Remarks:
     *   标题图URL
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_banner.title_url
     *
     * @mbg.generated 2019-11-06 09:49:13
     */
    private String titleUrl;

    /**
     * Database Column Remarks:
     *   跳转链接Url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_banner.redirect_url
     *
     * @mbg.generated 2019-11-06 09:49:13
     */
    private String redirectUrl;

    /**
     * Database Column Remarks:
     *   类型: 用户，活动，页面
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_banner.tyep
     *
     * @mbg.generated 2019-11-06 09:49:13
     */
    private String type;

    /**
     * Database Column Remarks:
     *   可用状态：Y/N
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_banner.status
     *
     * @mbg.generated 2019-11-06 09:49:13
     */
    private String status;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_banner.descp
     *
     * @mbg.generated 2019-11-06 09:49:13
     */
    private String descp;

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitleUrl() {
        return titleUrl;
    }

    public void setTitleUrl(String titleUrl) {
        this.titleUrl = titleUrl;
    }

    public String getRedirectUrl() {
        return redirectUrl;
    }

    public void setRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getDescp() {
        return descp;
    }

    public void setDescp(String descp) {
        this.descp = descp;
    }

    public com.wwd.service.modules.wwd.api.ApiWwdBannerService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.wwd.service.modules.wwd.api.ApiWwdBannerService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", title=").append(title);
        sb.append(", titleUrl=").append(titleUrl);
        sb.append(", redirectUrl=").append(redirectUrl);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append(", descp=").append(descp);
        sb.append("]");
        return sb.toString();
    }
}