package com.wwd.service.modules.wwd.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author revolver 2019-03-12 09:34:54
 *
 * This class corresponds to the database table wwd_participate
 * @mbg.generated do_not_delete_during_merge 2019-03-12 09:34:54
*/
public class WwdParticipate extends feihua.jdbc.api.pojo.BasePo<String> {
    /**
     * Database Column Remarks:
     *   活动ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_participate.wwd_activity_id
     *
     * @mbg.generated 2019-03-12 09:34:54
     */
    private String wwdActivityId;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_participate.wwd_user_id
     *
     * @mbg.generated 2019-03-12 09:34:54
     */
    private String wwdUserId;

    /**
     * Database Column Remarks:
     *   类型(是否是领队)：Y/N、
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_participate.type
     *
     * @mbg.generated 2019-03-12 09:34:54
     */
    private String type;

    /**
     * Database Column Remarks:
     *   支付状态：0/未支付，1/已支付，2/已退款
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_participate.pay_status
     *
     * @mbg.generated 2019-03-12 09:34:54
     */
    private String payStatus;

    /**
     * Database Column Remarks:
     *   状态：1/正常，2/替补，3/退出
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_participate.status
     *
     * @mbg.generated 2019-03-12 09:34:54
     */
    private String status;

    public String getWwdActivityId() {
        return wwdActivityId;
    }

    public void setWwdActivityId(String wwdActivityId) {
        this.wwdActivityId = wwdActivityId;
    }

    public String getWwdUserId() {
        return wwdUserId;
    }

    public void setWwdUserId(String wwdUserId) {
        this.wwdUserId = wwdUserId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getPayStatus() {
        return payStatus;
    }

    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public com.wwd.service.modules.wwd.api.ApiWwdParticipateService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.wwd.service.modules.wwd.api.ApiWwdParticipateService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", wwdActivityId=").append(wwdActivityId);
        sb.append(", wwdUserId=").append(wwdUserId);
        sb.append(", type=").append(type);
        sb.append(", payStatus=").append(payStatus);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}