package com.wwd.service.modules.wwd.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author revolver 2019-03-24 16:10:37
 *
 * This class corresponds to the database table wwd_participate
 * @mbg.generated do_not_delete_during_merge 2019-03-24 16:10:37
*/
public class WwdParticipate extends feihua.jdbc.api.pojo.BasePo<String> {
    /**
     * Database Column Remarks:
     *   活动ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_participate.wwd_activity_id
     *
     * @mbg.generated 2019-03-24 16:10:37
     */
    private String wwdActivityId;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_participate.wwd_user_id
     *
     * @mbg.generated 2019-03-24 16:10:37
     */
    private String wwdUserId;

    /**
     * Database Column Remarks:
     *   类型(是否是领队)：Y/N、
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_participate.type
     *
     * @mbg.generated 2019-03-24 16:10:37
     */
    private String type;

    /**
     * Database Column Remarks:
     *   支付状态：0/未支付，1/已支付，2/已退款
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_participate.pay_status
     *
     * @mbg.generated 2019-03-24 16:10:37
     */
    private String payStatus;

    /**
     * Database Column Remarks:
     *   状态：1/正常，2/替补，3/退出
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_participate.status
     *
     * @mbg.generated 2019-03-24 16:10:37
     */
    private String status;

    /**
     * Database Column Remarks:
     *   备注，退款。。。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_participate.remarks
     *
     * @mbg.generated 2019-03-24 16:10:37
     */
    private String remarks;

    /**
     * Database Column Remarks:
     *   报名人员姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_participate.name
     *
     * @mbg.generated 2019-03-24 16:10:37
     */
    private String name;

    /**
     * Database Column Remarks:
     *   报名人员手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_participate.mobile
     *
     * @mbg.generated 2019-03-24 16:10:37
     */
    private String mobile;

    public String getWwdActivityId() {
        return wwdActivityId;
    }

    public void setWwdActivityId(String wwdActivityId) {
        this.wwdActivityId = wwdActivityId;
    }

    public String getWwdUserId() {
        return wwdUserId;
    }

    public void setWwdUserId(String wwdUserId) {
        this.wwdUserId = wwdUserId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getPayStatus() {
        return payStatus;
    }

    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public com.wwd.service.modules.wwd.api.ApiWwdParticipateService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.wwd.service.modules.wwd.api.ApiWwdParticipateService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", wwdActivityId=").append(wwdActivityId);
        sb.append(", wwdUserId=").append(wwdUserId);
        sb.append(", type=").append(type);
        sb.append(", payStatus=").append(payStatus);
        sb.append(", status=").append(status);
        sb.append(", remarks=").append(remarks);
        sb.append(", name=").append(name);
        sb.append(", mobile=").append(mobile);
        sb.append("]");
        return sb.toString();
    }
}