package com.wwd.service.modules.wwd.po;

import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-06-17 17:59:28
 * Database Table Remarks:
 *   用户访问记录
 *
 * This class corresponds to the database table wwd_user_visit
 * @mbg.generated do_not_delete_during_merge 2019-06-17 17:59:28
*/
public class WwdUserVisit extends feihua.jdbc.api.pojo.BasePo<String> {
    /**
     * Database Column Remarks:
     *   被访问的用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_user_visit.wwd_user_id
     *
     * @mbg.generated 2019-06-17 17:59:28
     */
    private String wwdUserId;

    /**
     * Database Column Remarks:
     *   被访问wwd用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_user_visit.wwd_user_name
     *
     * @mbg.generated 2019-06-17 17:59:28
     */
    private String wwdUserName;

    /**
     * Database Column Remarks:
     *   被访问wwd用户性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_user_visit.wwd_user_gender
     *
     * @mbg.generated 2019-06-17 17:59:28
     */
    private String wwdUserGender;

    /**
     * Database Column Remarks:
     *   被访问wwd用户头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_user_visit.wwd_user_pic
     *
     * @mbg.generated 2019-06-17 17:59:28
     */
    private String wwdUserPic;

    /**
     * Database Column Remarks:
     *   访问的用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_user_visit.visit_wwd_user_id
     *
     * @mbg.generated 2019-06-17 17:59:28
     */
    private String visitWwdUserId;

    /**
     * Database Column Remarks:
     *   访问用户姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_user_visit.visit_wwd_user_name
     *
     * @mbg.generated 2019-06-17 17:59:28
     */
    private String visitWwdUserName;

    /**
     * Database Column Remarks:
     *   访问用户性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_user_visit.visit_wwd_user_gender
     *
     * @mbg.generated 2019-06-17 17:59:28
     */
    private String visitWwdUserGender;

    /**
     * Database Column Remarks:
     *   访问用户头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_user_visit.visit_wwd_user_pic
     *
     * @mbg.generated 2019-06-17 17:59:28
     */
    private String visitWwdUserPic;

    /**
     * Database Column Remarks:
     *   访问类型,例个人详情是从列表进，或分享（群，朋友圈等）进来，list,列表,timeline,朋友圈,groupmessage,微信群,singlemessage,好友分享
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_user_visit.visit_type
     *
     * @mbg.generated 2019-06-17 17:59:28
     */
    private String visitType;

    /**
     * Database Column Remarks:
     *   是否已读:Y/N
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wwd_user_visit.read_flag
     *
     * @mbg.generated 2019-06-17 17:59:28
     */
    private String readFlag;

    public String getWwdUserId() {
        return wwdUserId;
    }

    public void setWwdUserId(String wwdUserId) {
        this.wwdUserId = wwdUserId;
    }

    public String getWwdUserName() {
        return wwdUserName;
    }

    public void setWwdUserName(String wwdUserName) {
        this.wwdUserName = wwdUserName;
    }

    public String getWwdUserGender() {
        return wwdUserGender;
    }

    public void setWwdUserGender(String wwdUserGender) {
        this.wwdUserGender = wwdUserGender;
    }

    public String getWwdUserPic() {
        return wwdUserPic;
    }

    public void setWwdUserPic(String wwdUserPic) {
        this.wwdUserPic = wwdUserPic;
    }

    public String getVisitWwdUserId() {
        return visitWwdUserId;
    }

    public void setVisitWwdUserId(String visitWwdUserId) {
        this.visitWwdUserId = visitWwdUserId;
    }

    public String getVisitWwdUserName() {
        return visitWwdUserName;
    }

    public void setVisitWwdUserName(String visitWwdUserName) {
        this.visitWwdUserName = visitWwdUserName;
    }

    public String getVisitWwdUserGender() {
        return visitWwdUserGender;
    }

    public void setVisitWwdUserGender(String visitWwdUserGender) {
        this.visitWwdUserGender = visitWwdUserGender;
    }

    public String getVisitWwdUserPic() {
        return visitWwdUserPic;
    }

    public void setVisitWwdUserPic(String visitWwdUserPic) {
        this.visitWwdUserPic = visitWwdUserPic;
    }

    public String getVisitType() {
        return visitType;
    }

    public void setVisitType(String visitType) {
        this.visitType = visitType;
    }

    public String getReadFlag() {
        return readFlag;
    }

    public void setReadFlag(String readFlag) {
        this.readFlag = readFlag;
    }

    public com.wwd.service.modules.wwd.api.ApiWwdUserVisitService service() {
        return com.feihua.utils.spring.SpringContextHolder.getBean(com.wwd.service.modules.wwd.api.ApiWwdUserVisitService.class);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", wwdUserId=").append(wwdUserId);
        sb.append(", wwdUserName=").append(wwdUserName);
        sb.append(", wwdUserGender=").append(wwdUserGender);
        sb.append(", wwdUserPic=").append(wwdUserPic);
        sb.append(", visitWwdUserId=").append(visitWwdUserId);
        sb.append(", visitWwdUserName=").append(visitWwdUserName);
        sb.append(", visitWwdUserGender=").append(visitWwdUserGender);
        sb.append(", visitWwdUserPic=").append(visitWwdUserPic);
        sb.append(", visitType=").append(visitType);
        sb.append(", readFlag=").append(readFlag);
        sb.append("]");
        return sb.toString();
    }
}