package com.wwd.service.modules.wwd.api;

import com.wwd.service.modules.wwd.dto.WwdActivityUserMutualElectionDto;
import com.wwd.service.modules.wwd.po.WwdActivityUserMutualElectionPo;
import feihua.jdbc.api.pojo.PageResultDto;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-06-21 12:59:13
 */
public interface ApiWwdActivityUserMutualElectionPoService extends feihua.jdbc.api.service.ApiBaseService<WwdActivityUserMutualElectionPo, WwdActivityUserMutualElectionDto, String> {
    PageResultDto<WwdActivityUserMutualElectionDto> searchWwdActivityUserMutualElectionsDsf(com.wwd.service.modules.wwd.dto.SearchWwdActivityUserMutualElectionsConditionDto dto, feihua.jdbc.api.pojo.PageAndOrderbyParamDto pageAndOrderbyParamDto);
}