package com.wwd.service.modules.wwd.api;

import com.wwd.service.modules.wwd.dto.WwdUserVisitDto;
import com.wwd.service.modules.wwd.po.WwdUserVisit;
import feihua.jdbc.api.pojo.PageResultDto;

import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-06-17 13:29:29
 */
public interface ApiWwdUserVisitService extends feihua.jdbc.api.service.ApiBaseService<WwdUserVisit, WwdUserVisitDto, String> {
    PageResultDto<WwdUserVisitDto> searchWwdUserVisitsDsf(com.wwd.service.modules.wwd.dto.SearchWwdUserVisitsConditionDto dto, feihua.jdbc.api.pojo.PageAndOrderbyParamDto pageAndOrderbyParamDto);

    /**
     * nRead: 已看访问
     * yRead：未看访问
     * @param wwdUserId
     * @return map
     */
    Map selectVisitCountByWwdUserId(String wwdUserId);
}