package com.wwd.service.modules.wwd.api;

import com.wwd.service.modules.wwd.dto.WwdBannerDto;
import com.wwd.service.modules.wwd.po.WwdBanner;
import feihua.jdbc.api.pojo.PageResultDto;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-11-06 09:49:13
 */
public interface ApiWwdBannerService extends feihua.jdbc.api.service.ApiBaseService<WwdBanner, WwdBannerDto, String> {
    PageResultDto<WwdBannerDto> searchWwdBannersDsf(com.wwd.service.modules.wwd.dto.SearchWwdBannersConditionDto dto, feihua.jdbc.api.pojo.PageAndOrderbyParamDto pageAndOrderbyParamDto);
}