package com.wwd.service.modules.wwd.api;

import com.wwd.service.modules.wwd.dto.WwdUserParamQrcodeDto;
import com.wwd.service.modules.wwd.po.WwdUserParamQrcodePo;
import feihua.jdbc.api.pojo.BasePo;

/**
 * This class was generated by MyBatis Generator.
 * @author yangwei 2019-05-17 10:57:54
 */
public interface ApiWwdUserParamQrcodePoService extends feihua.jdbc.api.service.ApiBaseService<WwdUserParamQrcodePo, WwdUserParamQrcodeDto, String> {

    WwdUserParamQrcodePo selectByWwdUserIdAndIsLimit(String wwdUserId, BasePo.YesNo yesNo);
}