package com.wwd.service.modules.wwd.api;

import com.wwd.Constants;
import com.wwd.service.modules.wwd.dto.WwdParticipateDto;
import com.wwd.service.modules.wwd.po.WwdParticipate;
import feihua.jdbc.api.pojo.PageResultDto;

import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * @author revolver 2019-03-12 09:34:55
 */
public interface ApiWwdParticipateService extends feihua.jdbc.api.service.ApiBaseService<WwdParticipate, WwdParticipateDto, String> {

    PageResultDto<WwdParticipateDto> searchWwdParticipatesDsf(com.wwd.service.modules.wwd.dto.SearchWwdParticipatesConditionDto dto, feihua.jdbc.api.pojo.PageAndOrderbyParamDto pageAndOrderbyParamDto);

    List<WwdParticipate> selectByActivityIdAndWwdUserId(String activityId, String wwdUserId);
    List<WwdParticipate> selectByActivityIdAndWwdUserIdAndParticipateStatus(String activityId, String wwdUserId, Constants.WwdParticipateStatus wwdParticipateStatus);

    /**
     * 查询已支付的参与人员数据
     * @param activityId
     * @return
     */
    int selectCountPaidParticipate(String activityId);
    int selectCountPaidParticipate(String activityId,String gender);
}